version: "3.7"
services:
  myweb:
    build:
      context: .
      args:
        whoami: "Tony"
    image: john/myweb:latest
    ports:
      - "8080:80"
  myweb2:
    build:
      context: .
      args:
        whoami: "Chris"
    image: john/myweb1:latest
    ports:
      - "8081:80"
  myweb3:
    build:
      context: .
      args:
        whoami: "Jane"
    image: john/myweb2:latest
    ports:
      - "8082:80"
  myweb4:
    image: john/myweb:latest
    ports:
      - "8083:80"